[target.'cfg(target_arch = "x86_64")']
rustflags = [
    "-C", "link-arg=-nostartfiles",
]

[target.'cfg(target_arch = "x86")']
rustflags = [
    "-C", "link-arg=-nostartfiles",
]

[target.'cfg(target_arch = "aarch64")']
rustflags = [
    "-C", "link-arg=-nostartfiles",
]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-unknown-uefi"